FROM node:24-alpine AS builder
RUN apk add --no-cache git
WORKDIR /app
ARG CACHEBUST=1
RUN git clone https://github.com/SeraphInteractive/Platform-Discord.git .
RUN npm ci
RUN npm run build

FROM node:24-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/package*.json ./
RUN npm ci --omit=dev
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/data ./data

CMD ["node", "dist/index.js"]
